apiVersion: apps/v1
kind: Deployment
metadata:
  name: template
  labels:
    app: template
    version: v1
spec:
  selector:
    matchLabels:
      app: template
      version: v1
  template:
    metadata:
      labels:
        app: template
        version: v1
    spec:
      containers:
        - name: template
          image: pefish/template:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 1m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
      imagePullSecrets:
        - name: regcred
