apiVersion: v1
kind: Service
metadata:
  name: template
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: template
    version: v1
  type: NodePort
