name: CI

on: 
  create:
    tags:
      - 'v*.*.*'

env:
  USERNAME: pefish

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
    - name: checkout codes
      uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}
    - name: docker login
      run: |
        docker login -u "${{env.USERNAME}}" -p "${{ secrets.DOCKER_PASSWORD }}"
    - name: docker build
      run: |
        docker build -t ${{env.USERNAME}}/template:${{env.RELEASE_VERSION}} .
    - name: docker push
      run: |
        docker push ${{env.USERNAME}}/template:${{env.RELEASE_VERSION}}
    - name: kustomize build
      uses: docker://pefish/kustomize:latest
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: /bin/bash -c "kustomize build ./deploy | kubectl apply -f -"
    - name: deploy k8s
      uses: docker://pefish/kustomize:latest
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG }}
      with:
        args: /bin/bash -c "kubectl -n default set image deployment/frontend-template template=${{env.USERNAME}}/template:${{env.RELEASE_VERSION}}"

        